import type { ComplianceTask } from "@/types/compliance";

export const COMPLIANCE_SEED: ComplianceTask[] = [
  // ─── GASTRONOMIE – Hygiene & HACCP ───────────────────────────────────────
  {
    id: "g-001",
    titel: "HACCP-Eigenkontrollen dokumentieren",
    beschreibung:
      "Tägliche Temperaturmessung aller Kühl- und Tiefkühlgeräte protokollieren. Messwerte im HACCP-Formblatt eintragen, Abweichungen sofort melden.",
    kategorie: "Hygiene & HACCP",
    branche: "gastronomie",
    frist: "2026-05-12",
    wiederholung: "täglich",
    status: "offen",
    priorität: "hoch",
    erinnerungTage: 0,
    dokumente: ["haccp-temperaturprotokoll", "haccp-checkliste"],
  },
  {
    id: "g-002",
    titel: "Kühltemperaturen morgens & abends prüfen",
    beschreibung:
      "Kühlschrank ≤ 7 °C, Tiefkühl ≤ −18 °C. Bei Abweichung: Ware sicherstellen, Servicetechniker benachrichtigen und Vorfall schriftlich festhalten.",
    kategorie: "Hygiene & HACCP",
    branche: "gastronomie",
    frist: "2026-05-12",
    wiederholung: "täglich",
    status: "erledigt",
    priorität: "hoch",
    erinnerungTage: 0,
    dokumente: ["haccp-temperaturprotokoll"],
  },
  {
    id: "g-003",
    titel: "Schädlingsmonitoring & Protokollierung",
    beschreibung:
      "Fallen und Monitore auf Köder und Befall prüfen. Befund im Schädlingskontrollbuch eintragen. Bei Befall externen Schädlingsbekämpfer beauftragen.",
    kategorie: "Hygiene & HACCP",
    branche: "gastronomie",
    frist: "2026-06-01",
    wiederholung: "monatlich",
    status: "offen",
    priorität: "mittel",
    erinnerungTage: 7,
    dokumente: ["schaedlingsprotokoll"],
  },
  {
    id: "g-004",
    titel: "Hygienebelehrung Mitarbeiter (§ 43 IfSG)",
    beschreibung:
      "Jährliche Unterweisung aller Mitarbeiter mit Lebensmittelkontakt gemäß Infektionsschutzgesetz. Teilnahmeliste unterschreiben lassen und archivieren.",
    kategorie: "Hygiene & HACCP",
    branche: "gastronomie",
    frist: "2026-04-30",
    wiederholung: "jährlich",
    status: "überfällig",
    priorität: "hoch",
    erinnerungTage: 30,
    dokumente: ["hygienebelehrung-vorlage", "teilnahmeliste"],
  },
  {
    id: "g-005",
    titel: "Reinigungsplan überprüfen & aktualisieren",
    beschreibung:
      "Reinigungsplan auf Vollständigkeit und Aktualität prüfen. Neue Geräte, Küchenbereiche oder Produkte ergänzen. Mitarbeiter über Änderungen informieren.",
    kategorie: "Hygiene & HACCP",
    branche: "gastronomie",
    frist: "2026-05-31",
    wiederholung: "monatlich",
    status: "offen",
    priorität: "mittel",
    erinnerungTage: 7,
    dokumente: ["reinigungsplan-vorlage"],
  },
  // ─── GASTRONOMIE – Lebensmittelrecht ─────────────────────────────────────
  {
    id: "g-006",
    titel: "Allergenkennzeichnung Speisekarte prüfen",
    beschreibung:
      "Alle 14 Hauptallergene gemäß EU-Lebensmittelinformationsverordnung (LMIV) in der Speisekarte oder Aushang korrekt ausweisen. Rezepturänderungen sofort einpflegen.",
    kategorie: "Lebensmittelrecht",
    branche: "gastronomie",
    frist: "2026-05-20",
    wiederholung: "monatlich",
    status: "offen",
    priorität: "hoch",
    erinnerungTage: 14,
    dokumente: ["allergenliste-vorlage", "speisekarte-checkliste"],
  },
  {
    id: "g-007",
    titel: "Rückverfolgbarkeit Lieferantenbelege archivieren",
    beschreibung:
      "Alle Wareneingangsbelege der letzten 30 Tage auf Vollständigkeit prüfen. Lieferant, Produkt, Menge, Datum und Charge müssen lückenlos dokumentiert sein.",
    kategorie: "Lebensmittelrecht",
    branche: "gastronomie",
    frist: "2026-04-15",
    wiederholung: "monatlich",
    status: "überfällig",
    priorität: "mittel",
    erinnerungTage: 5,
    dokumente: ["wareneingang-protokoll"],
  },
  {
    id: "g-008",
    titel: "Lieferantenbewertung & Zulassungsprüfung",
    beschreibung:
      "Alle Lebensmittellieferanten auf gültige EU-Zulassung und Hygienezertifikate prüfen. Nicht zertifizierte Lieferanten schriftlich anfragen oder austauschen.",
    kategorie: "Lebensmittelrecht",
    branche: "gastronomie",
    frist: "2026-12-31",
    wiederholung: "jährlich",
    status: "offen",
    priorität: "mittel",
    erinnerungTage: 60,
    dokumente: ["lieferantenbewertung-vorlage"],
  },
  {
    id: "g-009",
    titel: "Zusatzstoffkennzeichnung kontrollieren",
    beschreibung:
      "Speisen mit zugelassenen Zusatzstoffen (z. B. Konservierungsstoffe, Farbstoffe) korrekt kennzeichnen. Änderungen in der Rezeptur sofort im Kennzeichnungssystem erfassen.",
    kategorie: "Lebensmittelrecht",
    branche: "gastronomie",
    frist: "2026-06-30",
    wiederholung: "jährlich",
    status: "offen",
    priorität: "niedrig",
    erinnerungTage: 30,
    dokumente: ["zusatzstoff-liste"],
  },
  // ─── GASTRONOMIE – Arbeitssicherheit ─────────────────────────────────────
  {
    id: "g-010",
    titel: "Gefährdungsbeurteilung Küche aktualisieren",
    beschreibung:
      "Alle Gefährdungen in Küche, Lager und Gastraum systematisch erfassen und bewerten. Schutzmaßnahmen festlegen und deren Wirksamkeit kontrollieren.",
    kategorie: "Arbeitssicherheit",
    branche: "gastronomie",
    frist: "2026-03-31",
    wiederholung: "jährlich",
    status: "überfällig",
    priorität: "hoch",
    erinnerungTage: 30,
    dokumente: ["gefaehrdungsbeurteilung-vorlage"],
  },
  {
    id: "g-011",
    titel: "Brandschutzübung & Evakuierungsplan",
    beschreibung:
      "Mindestens eine Brandschutzübung pro Jahr mit allen Mitarbeitern durchführen. Evakuierungsplan aktuell halten und gut sichtbar aushängen.",
    kategorie: "Arbeitssicherheit",
    branche: "gastronomie",
    frist: "2026-09-30",
    wiederholung: "jährlich",
    status: "offen",
    priorität: "mittel",
    erinnerungTage: 30,
    dokumente: ["evakuierungsplan-vorlage", "brandschutz-protokoll"],
  },
  {
    id: "g-012",
    titel: "Erste-Hilfe-Kurs Ersthelfer auffrischen",
    beschreibung:
      "Mindestens einen ausgebildeten Ersthelfer pro Schicht sicherstellen. Alle 2 Jahre Auffrischungskurs nachweisen. Erste-Hilfe-Kasten monatlich kontrollieren.",
    kategorie: "Arbeitssicherheit",
    branche: "gastronomie",
    frist: "2026-07-31",
    wiederholung: "jährlich",
    status: "offen",
    priorität: "mittel",
    erinnerungTage: 60,
    dokumente: ["ersthelfer-nachweis"],
  },
  // ─── GASTRONOMIE – Steuer & Buchführung ──────────────────────────────────
  {
    id: "g-013",
    titel: "Umsatzsteuer-Voranmeldung",
    beschreibung:
      "Monatliche USt-Voranmeldung fristgerecht beim Finanzamt einreichen. Vorsteuern sorgfältig belegen. Bei Überschreitung der Dauerfristverlängerung Sondervorauszahlung beachten.",
    kategorie: "Steuer & Buchführung",
    branche: "gastronomie",
    frist: "2026-05-30",
    wiederholung: "monatlich",
    status: "offen",
    priorität: "hoch",
    erinnerungTage: 10,
    dokumente: ["ust-voranmeldung-vorlage"],
  },
  {
    id: "g-014",
    titel: "Kassenbuch täglich führen & abschließen",
    beschreibung:
      "Tagesabschluss der Kasse dokumentieren, Kassenbestand mit Z-Bon abstimmen. Differenzen sofort erklären und schriftlich festhalten. 10 Jahre aufbewahren.",
    kategorie: "Steuer & Buchführung",
    branche: "gastronomie",
    frist: "2026-05-12",
    wiederholung: "täglich",
    status: "erledigt",
    priorität: "hoch",
    erinnerungTage: 0,
    dokumente: ["kassenbuch-vorlage"],
  },
  {
    id: "g-015",
    titel: "Jahresabschluss vorbereiten",
    beschreibung:
      "Belege sortieren, Inventur durchführen, Anlageverzeichnis aktualisieren. Unterlagen fristgerecht an Steuerberater übergeben.",
    kategorie: "Steuer & Buchführung",
    branche: "gastronomie",
    frist: "2026-12-31",
    wiederholung: "jährlich",
    status: "offen",
    priorität: "mittel",
    erinnerungTage: 60,
    dokumente: ["jahresabschluss-checkliste"],
  },
  {
    id: "g-016",
    titel: "GEZ Rundfunkbeitrag Betriebsstätte melden",
    beschreibung:
      "Betriebsstätten, Fahrzeuge und Empfangsgeräte korrekt beim Beitragsservice anmelden. Änderungen (neue Filiale, Fahrzeug, etc.) innerhalb eines Monats melden.",
    kategorie: "Steuer & Buchführung",
    branche: "gastronomie",
    frist: "2026-04-20",
    wiederholung: "jährlich",
    status: "überfällig",
    priorität: "niedrig",
    erinnerungTage: 14,
    dokumente: [],
  },

  // ─── HANDWERK – Arbeitssicherheit ────────────────────────────────────────
  {
    id: "h-001",
    titel: "Persönliche Schutzausrüstung (PSA) prüfen",
    beschreibung:
      "Alle PSA-Ausrüstungen (Helme, Sicherheitsschuhe, Schutzbrillen, Gehörschutz) auf Zustand, Ablaufdatum und Vollständigkeit prüfen. Defekte Ausrüstung sofort ersetzen.",
    kategorie: "Arbeitssicherheit",
    branche: "handwerk",
    frist: "2026-04-01",
    wiederholung: "jährlich",
    status: "überfällig",
    priorität: "hoch",
    erinnerungTage: 30,
    dokumente: ["psa-pruefliste"],
  },
  {
    id: "h-002",
    titel: "Elektrische Betriebsmittel prüfen (DGUV V3)",
    beschreibung:
      "Ortsveränderliche elektrische Betriebsmittel nach DGUV Vorschrift 3 durch Elektrofachkraft oder befähigte Person prüfen lassen. Prüfprotokoll und Prüfplakette anbringen.",
    kategorie: "Arbeitssicherheit",
    branche: "handwerk",
    frist: "2026-06-30",
    wiederholung: "jährlich",
    status: "offen",
    priorität: "hoch",
    erinnerungTage: 30,
    dokumente: ["dguv-v3-pruefprotokoll"],
  },
  {
    id: "h-003",
    titel: "Gerüste und Leitern monatlich inspizieren",
    beschreibung:
      "Alle Gerüste, Leitern und Aufstiegshilfen vor Benutzung und mindestens monatlich auf Beschädigungen, Stabilität und sichere Verankerung prüfen.",
    kategorie: "Arbeitssicherheit",
    branche: "handwerk",
    frist: "2026-05-31",
    wiederholung: "monatlich",
    status: "offen",
    priorität: "hoch",
    erinnerungTage: 5,
    dokumente: ["leiter-geruest-checkliste"],
  },
  {
    id: "h-004",
    titel: "Sicherheitsunterweisung Mitarbeiter",
    beschreibung:
      "Jährliche Sicherheitsunterweisung zu branchenspezifischen Gefährdungen (Absturz, Lärm, Chemikalien, Maschinen) für alle Mitarbeiter. Protokoll mit Unterschriften führen.",
    kategorie: "Arbeitssicherheit",
    branche: "handwerk",
    frist: "2026-11-30",
    wiederholung: "jährlich",
    status: "offen",
    priorität: "mittel",
    erinnerungTage: 30,
    dokumente: ["sicherheitsunterweisung-vorlage", "teilnahmeliste"],
  },
  {
    id: "h-005",
    titel: "Gefährdungsbeurteilung Baustellen aktualisieren",
    beschreibung:
      "Vor Beginn jeder neuen Baustelle sowie jährlich aktualisierte Gefährdungsbeurteilung erstellen. Besondere Gefährdungen (Asbest, Lärm, Absturz) gesondert bewerten.",
    kategorie: "Arbeitssicherheit",
    branche: "handwerk",
    frist: "2026-05-15",
    wiederholung: "jährlich",
    status: "überfällig",
    priorität: "hoch",
    erinnerungTage: 14,
    dokumente: ["gefaehrdungsbeurteilung-vorlage"],
  },
  // ─── HANDWERK – Meisterpflicht & Qualifikation ───────────────────────────
  {
    id: "h-006",
    titel: "Meisterbrief im Betrieb hinterlegen",
    beschreibung:
      "Kopie des Meisterbriefs des eingetragenen Betriebsleiters in der Betriebsstätte aufbewahren und auf Anfrage der Handwerkskammer vorlegen können.",
    kategorie: "Meisterpflicht & Qualifikation",
    branche: "handwerk",
    frist: "2026-01-01",
    wiederholung: "einmalig",
    status: "erledigt",
    priorität: "hoch",
    erinnerungTage: 0,
    dokumente: ["meisterbrief-kopie"],
  },
  {
    id: "h-007",
    titel: "Handwerksrolleneintrag prüfen & aktualisieren",
    beschreibung:
      "Eintragung in der Handwerksrolle (Anlage A) auf Aktualität prüfen. Änderungen (Betriebsleiter, Adresse, Gewerke) der Handwerkskammer melden.",
    kategorie: "Meisterpflicht & Qualifikation",
    branche: "handwerk",
    frist: "2026-12-31",
    wiederholung: "jährlich",
    status: "offen",
    priorität: "mittel",
    erinnerungTage: 30,
    dokumente: [],
  },
  {
    id: "h-008",
    titel: "Weiterbildungsnachweise aktualisieren",
    beschreibung:
      "Zertifikate und Nachweise über absolvierte Weiterbildungen (z. B. Energieeffizienz, neue Normen, Brandschutz) sammeln, archivieren und bei Ausschreibungen bereithalten.",
    kategorie: "Meisterpflicht & Qualifikation",
    branche: "handwerk",
    frist: "2026-12-31",
    wiederholung: "jährlich",
    status: "offen",
    priorität: "niedrig",
    erinnerungTage: 60,
    dokumente: ["weiterbildung-nachweis"],
  },
  {
    id: "h-009",
    titel: "Berufshaftpflichtversicherung erneuern",
    beschreibung:
      "Ablaufdatum der Berufshaftpflicht prüfen. Deckungssummen auf Ausreichendheit prüfen (Personenschäden ≥ 1 Mio. €). Neue Police rechtzeitig beauftragen.",
    kategorie: "Meisterpflicht & Qualifikation",
    branche: "handwerk",
    frist: "2026-06-30",
    wiederholung: "jährlich",
    status: "offen",
    priorität: "hoch",
    erinnerungTage: 45,
    dokumente: ["versicherungsnachweis"],
  },
  // ─── HANDWERK – Steuer & Buchführung ─────────────────────────────────────
  {
    id: "h-010",
    titel: "Umsatzsteuer-Voranmeldung",
    beschreibung:
      "Monatliche oder quartalsweise USt-Voranmeldung fristgerecht abgeben. Bauleistungen an andere Unternehmer: Reverse-Charge-Verfahren (§ 13b UStG) beachten.",
    kategorie: "Steuer & Buchführung",
    branche: "handwerk",
    frist: "2026-05-30",
    wiederholung: "monatlich",
    status: "offen",
    priorität: "hoch",
    erinnerungTage: 10,
    dokumente: ["ust-voranmeldung-vorlage"],
  },
  {
    id: "h-011",
    titel: "Fahrtenbuch & Reisekosten dokumentieren",
    beschreibung:
      "Für Firmenfahrzeuge täglichen Kilometerstand, Fahrtziel und Zweck eintragen. Bei Privatnutzung: 1-%-Regelung oder Fahrtenbuch korrekt führen.",
    kategorie: "Steuer & Buchführung",
    branche: "handwerk",
    frist: "2026-05-12",
    wiederholung: "täglich",
    status: "erledigt",
    priorität: "mittel",
    erinnerungTage: 0,
    dokumente: ["fahrtenbuch-vorlage"],
  },
  {
    id: "h-012",
    titel: "Lohnabrechnung & Sozialversicherungsmeldungen",
    beschreibung:
      "Monatliche Lohnabrechnungen erstellen, Sozialversicherungsbeiträge bis zum drittletzten Bankarbeitstag abführen. DEÜV-Meldungen fristgerecht übermitteln.",
    kategorie: "Steuer & Buchführung",
    branche: "handwerk",
    frist: "2026-05-28",
    wiederholung: "monatlich",
    status: "offen",
    priorität: "hoch",
    erinnerungTage: 5,
    dokumente: ["lohnabrechnung-checkliste"],
  },
  {
    id: "h-013",
    titel: "Betriebsprüfungsunterlagen 10 Jahre aufbewahren",
    beschreibung:
      "Buchhaltungsunterlagen, Rechnungen, Verträge und Belege gemäß GoBD 10 Jahre aufbewahren. Digitale Ablage GoBD-konform organisieren.",
    kategorie: "Steuer & Buchführung",
    branche: "handwerk",
    frist: "2026-12-31",
    wiederholung: "jährlich",
    status: "offen",
    priorität: "mittel",
    erinnerungTage: 30,
    dokumente: ["aufbewahrungspflichten-checkliste"],
  },

  // ─── GESUNDHEITSWESEN – Datenschutz & DSGVO ──────────────────────────────
  {
    id: "ges-001",
    titel: "Verarbeitungsverzeichnis (Art. 30 DSGVO) aktualisieren",
    beschreibung:
      "Alle Datenverarbeitungstätigkeiten im Verzeichnis dokumentieren und aktuell halten. Neue Software, Anbieter oder Verarbeitungszwecke sofort ergänzen.",
    kategorie: "Datenschutz & DSGVO",
    branche: "gesundheitswesen",
    frist: "2026-04-10",
    wiederholung: "jährlich",
    status: "überfällig",
    priorität: "hoch",
    erinnerungTage: 30,
    dokumente: ["verarbeitungsverzeichnis-vorlage"],
  },
  {
    id: "ges-002",
    titel: "Datenschutzschulung Praxismitarbeiter",
    beschreibung:
      "Jährliche DSGVO-Schulung für alle Mitarbeiter mit Patientendatenzugang. Inhalte: Schweigeflicht, Zugriffsrechte, Meldepflichten bei Datenpannen.",
    kategorie: "Datenschutz & DSGVO",
    branche: "gesundheitswesen",
    frist: "2026-05-25",
    wiederholung: "jährlich",
    status: "offen",
    priorität: "hoch",
    erinnerungTage: 30,
    dokumente: ["datenschutz-schulungsprotokoll", "teilnahmeliste"],
  },
  {
    id: "ges-003",
    titel: "Auftragsverarbeitungsverträge (AVV) prüfen",
    beschreibung:
      "Alle AVV mit IT-Dienstleistern, Laboren und externen Abrechnungsstellen auf Aktualität prüfen. Neue Dienstleister vor Auftragserteilung mit AVV versehen.",
    kategorie: "Datenschutz & DSGVO",
    branche: "gesundheitswesen",
    frist: "2026-09-30",
    wiederholung: "jährlich",
    status: "offen",
    priorität: "mittel",
    erinnerungTage: 60,
    dokumente: ["avv-vorlage"],
  },
  {
    id: "ges-004",
    titel: "Datenschutz-Folgenabschätzung (DSFA) prüfen",
    beschreibung:
      "Bei hochriskanten Verarbeitungen (z. B. genetische Daten, KI-gestützte Diagnose) DSFA durchführen oder aktualisieren. Ergebnis dokumentieren und Aufsichtsbehörde bei Bedarf konsultieren.",
    kategorie: "Datenschutz & DSGVO",
    branche: "gesundheitswesen",
    frist: "2026-10-31",
    wiederholung: "jährlich",
    status: "offen",
    priorität: "mittel",
    erinnerungTage: 60,
    dokumente: ["dsfa-vorlage"],
  },
  // ─── GESUNDHEITSWESEN – Hygiene & Infektionsschutz ───────────────────────
  {
    id: "ges-005",
    titel: "Hygieneplan aktualisieren (§ 36 IfSG)",
    beschreibung:
      "Hygieneplan mindestens jährlich aktualisieren und neuen Mitarbeitern aushändigen. Aktuelle RKI-Empfehlungen und Landesverordnungen berücksichtigen.",
    kategorie: "Hygiene & Infektionsschutz",
    branche: "gesundheitswesen",
    frist: "2026-04-30",
    wiederholung: "jährlich",
    status: "überfällig",
    priorität: "hoch",
    erinnerungTage: 30,
    dokumente: ["hygieneplan-vorlage"],
  },
  {
    id: "ges-006",
    titel: "Infektionsschutzbelehrung (§ 35 IfSG) Mitarbeiter",
    beschreibung:
      "Alle Mitarbeiter mit Patientenkontakt jährlich über Infektionsvermeidung, Meldepflichten und Hygienemaßnahmen belehren. Unterschriften sammeln.",
    kategorie: "Hygiene & Infektionsschutz",
    branche: "gesundheitswesen",
    frist: "2026-06-30",
    wiederholung: "jährlich",
    status: "offen",
    priorität: "hoch",
    erinnerungTage: 30,
    dokumente: ["ifsg-belehrung-vorlage", "teilnahmeliste"],
  },
  {
    id: "ges-007",
    titel: "Desinfektionsmittel-Lager & Verfallsdaten prüfen",
    beschreibung:
      "Bestand aller Desinfektionsmittel prüfen, Verfallsdaten kontrollieren, VAH-Listung sicherstellen. Abgelaufene Mittel entsorgen und nachbestellen.",
    kategorie: "Hygiene & Infektionsschutz",
    branche: "gesundheitswesen",
    frist: "2026-05-31",
    wiederholung: "monatlich",
    status: "offen",
    priorität: "mittel",
    erinnerungTage: 7,
    dokumente: ["desinfektionsmittel-liste"],
  },
  {
    id: "ges-008",
    titel: "Händehygiene-Audit durchführen",
    beschreibung:
      "Beobachtungsaudit zur Händehygiene-Compliance des Teams. Verbrauch von Händedesinfektionsmittel dokumentieren und mit WHO-Empfehlungen abgleichen.",
    kategorie: "Hygiene & Infektionsschutz",
    branche: "gesundheitswesen",
    frist: "2026-06-30",
    wiederholung: "monatlich",
    status: "offen",
    priorität: "mittel",
    erinnerungTage: 14,
    dokumente: ["haendehygiene-auditbogen"],
  },
  // ─── GESUNDHEITSWESEN – Arzneimittel & Medizinprodukte ───────────────────
  {
    id: "ges-009",
    titel: "Medizinprodukteregister (MPDG) führen",
    beschreibung:
      "Alle Medizinprodukte in einem Bestandsverzeichnis erfassen. UDI, Seriennummer, Hersteller, Klasse und Anschaffungsdatum dokumentieren.",
    kategorie: "Arzneimittel & Medizinprodukte",
    branche: "gesundheitswesen",
    frist: "2026-12-31",
    wiederholung: "jährlich",
    status: "offen",
    priorität: "mittel",
    erinnerungTage: 60,
    dokumente: ["medizinprodukte-register"],
  },
  {
    id: "ges-010",
    titel: "Einweisung Medizinprodukte dokumentieren",
    beschreibung:
      "Alle Anwender in neue oder geänderte Medizinprodukte einweisen. Einweisung durch Hersteller oder befähigte Person mit Datum und Unterschrift protokollieren.",
    kategorie: "Arzneimittel & Medizinprodukte",
    branche: "gesundheitswesen",
    frist: "2026-03-15",
    wiederholung: "jährlich",
    status: "überfällig",
    priorität: "hoch",
    erinnerungTage: 30,
    dokumente: ["einweisungsprotokoll-vorlage"],
  },
  {
    id: "ges-011",
    titel: "Verfallsdaten Arzneimittelvorrat kontrollieren",
    beschreibung:
      "Alle Arzneimittel im Notfallkoffer, Praxisvorrat und Impfstoff-Kühlschrank auf Verfallsdaten prüfen. Abgelaufene Mittel fachgerecht entsorgen und nachbestellen.",
    kategorie: "Arzneimittel & Medizinprodukte",
    branche: "gesundheitswesen",
    frist: "2026-05-31",
    wiederholung: "monatlich",
    status: "offen",
    priorität: "hoch",
    erinnerungTage: 5,
    dokumente: ["arzneimittel-pruefprotokoll"],
  },
  // ─── GESUNDHEITSWESEN – Qualitätsmanagement ──────────────────────────────
  {
    id: "ges-012",
    titel: "Qualitätsmanagement-Handbuch Review (§ 135a SGB V)",
    beschreibung:
      "QM-Handbuch jährlich auf Aktualität prüfen, Abweichungen dokumentieren, Verbesserungsmaßnahmen ableiten und Umsetzung kontrollieren.",
    kategorie: "Qualitätsmanagement",
    branche: "gesundheitswesen",
    frist: "2026-06-30",
    wiederholung: "jährlich",
    status: "offen",
    priorität: "mittel",
    erinnerungTage: 30,
    dokumente: ["qm-handbuch", "qm-review-protokoll"],
  },
  {
    id: "ges-013",
    titel: "Beschwerdemanagement auswerten",
    beschreibung:
      "Eingegangene Patientenbeschwerden monatlich auswerten, kategorisieren und Verbesserungsmaßnahmen ableiten. Trend-Analyse für Jahresbericht vorbereiten.",
    kategorie: "Qualitätsmanagement",
    branche: "gesundheitswesen",
    frist: "2026-05-31",
    wiederholung: "monatlich",
    status: "offen",
    priorität: "niedrig",
    erinnerungTage: 7,
    dokumente: ["beschwerde-auswertung-vorlage"],
  },
  {
    id: "ges-014",
    titel: "Fortbildungsnachweise Ärzte (CME-Punkte) prüfen",
    beschreibung:
      "Sicherstellen, dass alle Ärzte die erforderlichen 250 CME-Punkte im 5-Jahres-Zeitraum nachweisen können. Zertifikate sammeln und bei der Ärztekammer einreichen.",
    kategorie: "Qualitätsmanagement",
    branche: "gesundheitswesen",
    frist: "2026-12-31",
    wiederholung: "jährlich",
    status: "offen",
    priorität: "mittel",
    erinnerungTage: 90,
    dokumente: ["cme-nachweis-vorlage"],
  },
  {
    id: "ges-015",
    titel: "Praxisbegehung durch Kassenärztliche Vereinigung vorbereiten",
    beschreibung:
      "Alle relevanten Unterlagen (QM-Handbuch, Hygieneplan, Medizinprodukteregister, Datenschutzdokumentation) für die KV-Begehung zusammenstellen und aktualisieren.",
    kategorie: "Qualitätsmanagement",
    branche: "gesundheitswesen",
    frist: "2026-09-30",
    wiederholung: "jährlich",
    status: "offen",
    priorität: "mittel",
    erinnerungTage: 60,
    dokumente: ["begehung-checkliste"],
  },
];
